---
- name: add groups
  hosts: all 
  user: root
  tasks:
  - name: add list of users
    user:
      name: "{{ item }}"
      state: present
    with_items:
    - ben
    - lisa
    - kate
    - dan
    - sam