---
- name: Install Web Server
  hosts: all 
  user: root
  tasks:
  - name: install apache
    yum:
      name: httpd
      state: latest
  - name: start httpd
    service:
      name: httpd
      state: started
      enabled: yes
  - name: host hello world          
    shell: "echo 'Hello World' > /var/www/html/index.html" 